/*
 Copyright Notice and Disclaimer
 -------------------------------
(c) Copyright 2013.
SAP AG or an SAP affiliate company. All rights reserved.
Unpublished rights reserved under U.S. copyright laws.

SAP grants Licensee a non-exclusive license to use, reproduce,
modify, and distribute the sample source code below (the "Sample Code"),
subject to the following conditions:

(i) redistributions must retain the above copyright notice;

(ii) SAP shall have no obligation to correct errors or deliver
updates to the Sample Code or provide any other support for the
Sample Code;

(iii) Licensee may use the Sample Code to develop applications
(the "Licensee Applications") and may distribute the Sample Code in
whole or in part as part of such Licensee Applications, however in no
event shall Licensee distribute the Sample Code on a standalone basis;

(iv) and subject to the following disclaimer:
THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
SAP AG or an SAP affiliate company OR ITS LICENSORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
USE OF THE SAMPLE CODE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.
*/

package sybase.sample;
import java.io.*;
import java.sql.*;
import java.util.*;

/**
 * MyDriver class Demonstrates the use of the Driver and DriverPropertyInfo
 * classes.<br>
 *
 * <P>MyDriver may be invoked with the optional parameters:<br>
 * -U username<br>
 * -P password<br>
 * -D debuglibraries<br>
 * -S server<p>
 *
 *  @see Sample
 */
public class MyDriver extends Sample
{
    static Driver _driver = null; 
    static String _url = null; 
    static Properties _props = null;

    MyDriver()
    {
        super();
    }

    public void run()
    {

        try
        {

            addMoreProps(_cmdline);

            // Save off the data we will need in SampleCode()

            _url = _cmdline._props.getProperty("server");
            _props = _cmdline._props;

            // Load the Driver

            DriverManager.registerDriver((Driver)
                Class.forName("com.sybase.jdbc4.jdbc.SybDriver").newInstance());

            _driver = DriverManager.getDriver(_url);


            //Connect using the Driver.connect()

            _con = _driver.connect(_url, _props);

            // Check for, and display and warnings generated by the connect.
            checkForWarning (_con.getWarnings ());

            // Run the sample specific code
            sampleCode();

            // Close the connection
            _con.close();
        }
        catch (SQLException ex)
        {
            displaySQLEx(ex);
        }
        catch (java.lang.Exception ex)
        {
            /*
          *  Got some other type of exception.  Dump it.
          */
            ex.printStackTrace ();
        }
    }

    public void sampleCode()
    {


        try
        {

            // Display the key info from the driver

            output("acceptsURL(" + _url +")= " +
                _driver.acceptsURL(_url) + "\n");
            output("getMajorVersion()= " + _driver.getMajorVersion() 
                + "\n");
            output("getMinorVersion()= " + _driver.getMinorVersion() 
                + "\n");
            output("jdbcCompliant()= " + _driver.jdbcCompliant() 
                + "\n");
            DriverPropertyInfo dpi[] = _driver.getPropertyInfo(
                _url, _props);

            // Display the jConnect properties

            output("jConnect Driver Properties\n");
            for (int i = 0; i < dpi.length; i++)
            {
                output(dpi[i].name +"\t\t");
                output(dpi[i].value +"\t\t");
                output(dpi[i].description  + "\n");
            }



        }
        catch (Exception ex)
        {

            ex.printStackTrace ();
        }
    }
}
